# Form implementation generated from reading ui file 'c:\Users\Laptop\Google Drive\Facial_Recog\main\cams.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.block = QtWidgets.QPushButton(Form)
        self.block.setGeometry(QtCore.QRect(120, 40, 141, 51))
        self.block.setObjectName("block")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(120, 140, 141, 51))
        self.add.setObjectName("add")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(130, 230, 131, 51))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.block.setText(_translate("Form", "BLOCK"))
        self.add.setText(_translate("Form", "ADD"))
        self.exit.setText(_translate("Form", "EXIT"))
