# Form implementation generated from reading ui file 'c:\Users\Laptop\Google Drive\Facial_Recog\main\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 569)
        self.cams = QtWidgets.QPushButton(Form)
        self.cams.setGeometry(QtCore.QRect(100, 230, 151, 81))
        self.cams.setObjectName("cams")
        self.list = QtWidgets.QPushButton(Form)
        self.list.setGeometry(QtCore.QRect(360, 230, 171, 81))
        self.list.setObjectName("list")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 30, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.settings = QtWidgets.QPushButton(Form)
        self.settings.setGeometry(QtCore.QRect(260, 390, 93, 28))
        self.settings.setObjectName("settings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cams.setText(_translate("Form", "Show all Camera"))
        self.list.setText(_translate("Form", "blocked"))
        self.label.setText(_translate("Form", "Security system"))
        self.settings.setText(_translate("Form", "settings"))
