############### STARTING OF THE PROGRAMME ######################################################
import sys
from PyQt6 import QtGui
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QApplication, QWidget , QLabel, QVBoxLayout
from PyQt6.QtCore import Qt
from PyQt6 import uic
from PyQt6.QtCore import pyqtSignal, pyqtSlot, Qt, QThread
from face_rec import runcam2
from ui_imp_facerecog import VideoThread
import numpy as np
import cv2

class MyApp(QWidget):
    def __init__(self) :
        super().__init__()
        uic.loadUi('GUI.ui',self)
        
        self.cams.clicked.connect(self.runcam)
        self.cams.clicked.connect(runcam2)

    def runcam(self):
            runcam2
            cams.show()
            

class MyCam(QWidget):
    def __init__(self):
         super().__init__()
         uic.loadUi('cams.ui',self)
         runcam2
app = QApplication(sys.argv)

myApp = MyApp()
myApp.show()

cams = MyCam()

sys.exit(app.exec())


##################################### running the facial recognition software ##################
import face_recognition
import cv2
import numpy as np

def runcam2():
    


    video_capture = cv2.VideoCapture('security.mp4')
    obama = face_recognition.load_image_file("obama.jpg")
    obama_enc = face_recognition.face_encodings(obama)[0]

    biden = face_recognition.load_image_file("biden.jpg")
    biden_enc = obama_enc = face_recognition.face_encodings(biden)[0]

    ashish = face_recognition.load_image_file("ashish.jpg")
    ashish_enc = face_recognition.face_encodings(ashish)[0]

    known_enc = [
    obama_enc,
    biden_enc,
    ashish_enc

    ]

    known_face = [
    "obama",
    "biden",
    'ashish'
    ]

    face_locations = []
    face_encodings = []
    face_names = []
    process_this_frame = True

    while True :
        ret, frame = video_capture.read()
        if process_this_frame:

            small_frame = cv2.resize(frame,(0,0),fx=0.25,fy=0.25)

            rgb_small_frame = small_frame[:,:,::-1]

            face_locations = face_recognition.face_locations(rgb_small_frame)
            face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)\

            face_names = []
            for face_encoding in face_encodings:
                matches = face_recognition.compare_faces(known_enc,face_encoding)
                name = 'unknown'

                face_distances = face_recognition.face_distance(known_enc,face_encoding)
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    name = known_face[best_match_index]

                face_names.append(name)

        process_this_frame = not process_this_frame

        for (top, right, bottom, left),name in zip(face_locations,face_names):
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4
        
            cv2.rectangle(frame, (left,top),(right,bottom),(0,0,255),2)
            font = cv2.FONT_HERSHEY_COMPLEX
            cv2.putText(frame,name,(left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

        cv2.imshow('Video',frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    video_capture.release()
    cv2.destroyAllWindows()

#################################### UI code for the main dashboard ############################
    # Form implementation generated from reading ui file 'c:\Users\Laptop\Google Drive\Facial_Recog\main\GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 569)
        self.cams = QtWidgets.QPushButton(Form)
        self.cams.setGeometry(QtCore.QRect(100, 230, 151, 81))
        self.cams.setObjectName("cams")
        self.list = QtWidgets.QPushButton(Form)
        self.list.setGeometry(QtCore.QRect(360, 230, 171, 81))
        self.list.setObjectName("list")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 30, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.settings = QtWidgets.QPushButton(Form)
        self.settings.setGeometry(QtCore.QRect(260, 390, 93, 28))
        self.settings.setObjectName("settings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cams.setText(_translate("Form", "Show all Camera"))
        self.list.setText(_translate("Form", "blocked"))
        self.label.setText(_translate("Form", "Security system"))
        self.settings.setText(_translate("Form", "settings"))

############################### UI code for camera setup #######################################

# Form implementation generated from reading ui file 'c:\Users\Laptop\Google Drive\Facial_Recog\main\GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 569)
        self.cams = QtWidgets.QPushButton(Form)
        self.cams.setGeometry(QtCore.QRect(100, 230, 151, 81))
        self.cams.setObjectName("cams")
        self.list = QtWidgets.QPushButton(Form)
        self.list.setGeometry(QtCore.QRect(360, 230, 171, 81))
        self.list.setObjectName("list")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 30, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.settings = QtWidgets.QPushButton(Form)
        self.settings.setGeometry(QtCore.QRect(260, 390, 93, 28))
        self.settings.setObjectName("settings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cams.setText(_translate("Form", "Show all Camera"))
        self.list.setText(_translate("Form", "blocked"))
        self.label.setText(_translate("Form", "Security system"))
        self.settings.setText(_translate("Form", "settings"))

