# Form implementation generated from reading ui file 'c:\Users\Laptop\Google Drive\Facial_Recog\stuff\un.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        self.vid = QtWidgets.QLabel(Form)
        self.vid.setGeometry(QtCore.QRect(360, 60, 711, 531))
        self.vid.setText("")
        self.vid.setPixmap(QtGui.QPixmap("c:\\Users\\Laptop\\Google Drive\\Facial_Recog\\stuff\\../main/wallppaer.jpg"))
        self.vid.setObjectName("vid")
        self.block = QtWidgets.QPushButton(Form)
        self.block.setGeometry(QtCore.QRect(320, 640, 93, 28))
        self.block.setObjectName("block")
        self.enter = QtWidgets.QPushButton(Form)
        self.enter.setGeometry(QtCore.QRect(640, 640, 93, 28))
        self.enter.setObjectName("enter")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(940, 640, 93, 28))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.block.setText(_translate("Form", "block"))
        self.enter.setText(_translate("Form", "Enter"))
        self.exit.setText(_translate("Form", "scan"))
